/**
 * OpenAPI → TypeScript 타입 생성 스크립트.
 *
 * 1) python studio/openapi_dump.py        → studio OpenAPI JSON
 * 2) python identifier/openapi_dump.py    → identifier OpenAPI JSON
 * 3) openapi-typescript 프로그램 API로    → packages/shared/src/api-types/{studio,identifier}.ts
 *
 * 실행: pnpm gen:types
 * CI 드리프트 체크: pnpm gen:types:check
 *
 * 환경변수:
 *   PYTHON_BIN              — 사용할 python 실행 파일 (기본: python3)
 *   STUDIO_DUMP_CMD         — studio dump를 대체 실행 (예: "docker compose exec -T studio python studio/openapi_dump.py")
 *   IDENTIFIER_DUMP_CMD     — identifier dump를 대체 실행
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../..");
const OUT_DIR = path.resolve(__dirname, "../packages/shared/src/api-types");

type Target = {
  name: "studio" | "identifier";
  envOverride: string;
  module: string;
};

const TARGETS: Target[] = [
  { name: "studio", envOverride: "STUDIO_DUMP_CMD", module: "studio.openapi_dump" },
  { name: "identifier", envOverride: "IDENTIFIER_DUMP_CMD", module: "identifier.openapi_dump" },
];

function dumpOpenAPI(target: Target): string {
  const override = process.env[target.envOverride];
  if (override) {
    const result = spawnSync(override, { shell: true, cwd: REPO_ROOT, encoding: "utf8" });
    if (result.status !== 0) {
      throw new Error(`[${target.name}] dump override failed: ${result.stderr}`);
    }
    return result.stdout;
  }

  const pythonBin = process.env.PYTHON_BIN ?? "python3";
  const result = spawnSync(pythonBin, ["-m", target.module], {
    cwd: REPO_ROOT,
    encoding: "utf8",
    env: { ...process.env, PYTHONPATH: REPO_ROOT },
  });
  if (result.status !== 0) {
    throw new Error(
      `[${target.name}] ${pythonBin} -m ${target.module} failed (status=${result.status}):\n${result.stderr}`,
    );
  }
  return result.stdout;
}

async function generate(target: Target): Promise<void> {
  const json = dumpOpenAPI(target);
  const schema = JSON.parse(json);
  const ast = await openapiTS(schema);
  const ts = astToString(ast);

  mkdirSync(OUT_DIR, { recursive: true });
  const outFile = path.join(OUT_DIR, `${target.name}.ts`);
  const header = `/* eslint-disable */
/**
 * AUTO-GENERATED by frontend/scripts/gen-types.ts.
 * 수정 금지 — 대신 서버측 Pydantic 스키마를 바꾸고 \`pnpm gen:types\`를 다시 실행하세요.
 */

`;
  writeFileSync(outFile, header + ts, "utf8");
  console.log(`✓ ${target.name} → ${path.relative(REPO_ROOT, outFile)}`);
}

async function main(): Promise<void> {
  for (const target of TARGETS) {
    await generate(target);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
